# Koby Hass
## 3/23/2021
### Numpy array processing in python

In [1]:
import numpy as np

In [2]:
mylist = [11,22,33,44,55,66,77]

print(mylist)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
myarr = np.array(mylist)

In [5]:
print(myarr.dtype)

int32


In [6]:
fruits = ['Orange', 'Apple', 'Cherry', 'Grape']

mystrArr = np.array(fruits)

In [8]:
print(mystrArr.dtype)

<U6


In [10]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')

In [11]:
print(my_arr2.dtype)

|S2


In [12]:
my_arr3 = np.array([5,6,7,8,9], dtype='i4')

In [13]:
print(my_arr3.dtype)

int32


In [14]:
myerrArr = np.array(['1','2','3','4','5'], dtype = 'i')
print(myerrArr.dtype)

int32


In [15]:
print(myerrArr)

[1 2 3 4 5]


In [16]:
scores = [78.5,88.9,90.3,89.9]

my_arr = np.array(scores)

In [17]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [18]:
arr = my_arr.astype('i')

In [19]:
arr

array([78, 88, 90, 89], dtype=int32)

In [20]:
arr = np.array([1,0,0,3,4,5,6,7,0])

print(arr.dtype)

int32


In [21]:
bool_arr = arr.astype(bool)


In [22]:
print(bool_arr)

[ True False False  True  True  True  True  True False]


In [23]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [24]:
my_list = [11,12,13,14,15]

arr = np.array(my_list)
c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [25]:
arr[3] = 4
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [26]:
my_list = [11,12,13,14,15]

arr = np.array(my_list)
c_arr = arr.view()

print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [27]:
arr[3]=4
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13  4 15]


In [28]:
c_arr[2] = 3
print(arr)
print(c_arr)

[11 12  3  4 15]
[11 12  3  4 15]


In [29]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)
print(my_arr)
print(my_arr.shape)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
(2, 5)


In [ ]:
arr = np.array