# Koby Hass
## 4/2/2021
### Python NumPy Universal Functions

In [4]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]

z = []

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [5]:
fname = ("Lilith", "Buffy", "Spike")
lname = ("Luna", "Summers", "William")

flname = zip(fname, lname)
print(tuple(flname))

(('Lilith', 'Luna'), ('Buffy', 'Summers'), ('Spike', 'William'))


In [6]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [7]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
arr1 = np.random.randn(10)
arr1

array([ 1.09361385, -0.56164832, -1.18674073, -0.65424969, -0.71327974,
       -0.74111364, -0.27707974,  0.54958353, -0.19558795, -1.1906599 ])

In [12]:
arr2 = np.random.randn(10)

arr2

array([-1.08904234, -0.97781981, -0.55535637,  1.27912156,  0.08855841,
       -0.52533992,  0.21661819, -1.26948172,  1.12870701,  0.32820675])

In [13]:
np.add(arr1,arr2)

array([ 0.00457151, -1.53946813, -1.7420971 ,  0.62487186, -0.62472133,
       -1.26645356, -0.06046155, -0.71989819,  0.93311906, -0.86245316])

In [14]:
np.maximum(arr1,arr2)

array([ 1.09361385, -0.56164832, -0.55535637,  1.27912156,  0.08855841,
       -0.52533992,  0.21661819,  0.54958353,  1.12870701,  0.32820675])

In [15]:
arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
print(arr<4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [17]:
np.where(arr < 4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [18]:
np.where((arr<4)& (arr>2), -1 , -2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True, False, True, True, False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [21]:
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]